### ISSUE TITLE
How can I use this source?

### ISSUE THREAD

**Issue by perfectdeveloper53** [pesse/gwt-jsinterop-threejs#2]
Hello. I am interested in your repository.

Can you tell me how I can use this repo?  I want to integrate three.js to android native, so I want to use this as possible.  Kindly response in fast time.

**Comment by perfectdeveloper53** [comment]
@pesse  Please help me

**Comment by pesse** [comment]
The repo is more of a study. It's far from finished and I don't plan to put any more work into it.
It's there as example how interoperability between Java/GWT and an existing JavaScript library could be done.
I'm not into android development, but you might want to have a look if it can be compiled with Graal, which will be the future answer to any Java/JavaScript interoperabilities.
